<?php

namespace Trinityrank\GeoLocation;

use Laravel\Nova\Panel;
use OptimistDigital\MultiselectField\Multiselect;
use OwenMelbz\RadioField\RadioButton;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Fields\Badge;

class GeoLocationPanel
{

    public static function make($panelTitle = 'GeoLocation Page Settings', $columnName = null, $targets = null, $options = null)
    {
        // Because we have conditional fields
        if( isset($options['visibility']) && $options['visibility'] == false )
        {
            return new Panel($panelTitle, []);
        }

        return new Panel($panelTitle, [
            // Only on forms fields
            RadioButton::make('Choose:', 'geolocation_option')
                ->options([
                    1 => 'Show in',
                    2 => 'Never show in',
                ])
                ->default(0)
                ->stack()
                ->marginBetween()
                ->onlyOnForms(),

            self::multiselect('Select Countries', 'geolocation_countries'),

            // Except on form fields
            RadioButton::make('Geolocation Option:', 'geolocation_option')
            ->options([
                0 => '',
                1 => 'Show in countries',
                2 => 'Hide in countries',
            ])
            ->exceptOnForms(),

            Text::make('Countries', function ($locations) {
                return join(", ", json_decode($locations->geolocation_countries));
            })->exceptOnForms(),
        ]);

    }
    

    public static function multiselect($title, $field_name)
    {
        return Multiselect::make($title, $field_name)
            ->options([
                "AD" => "Andorra",
                "AE" => "United Arab Emirates",
                "AF" => "Afghanistan",
                "AG" => "Antigua and Barbuda",
                "AI" => "Anguilla",
                "AL" => "Albania",
                "AM" => "Armenia",
                "AO" => "Angola",
                "AR" => "Argentina",
                "AS" => "American Samoa",
                "AT" => "Austria",
                "AU" => "Australia",
                "AW" => "Aruba",
                "AX" => "Aland Islands",
                "AZ" => "Azerbaijan",
                "BA" => "Bosnia and Herzegovina",
                "BB" => "Barbados",
                "BD" => "Bangladesh",
                "BE" => "Belgium",
                "BF" => "Burkina Faso",
                "BG" => "Bulgaria",
                "BH" => "Bahrain",
                "BI" => "Burundi",
                "BJ" => "Benin",
                "BL" => "Saint Barthelemy",
                "BM" => "Bermuda",
                "BN" => "Brunei Darussalam",
                "BO" => "Bolivia (Plurinational State of)",
                "BQ" => "Bonaire, Sint Eustatius and Saba",
                "BR" => "Brazil",
                "BS" => "Bahamas",
                "BT" => "Bhutan",
                "BW" => "Botswana",
                "BY" => "Belarus",
                "BZ" => "Belize",
                "CA" => "Canada",
                "CD" => "Congo (Democratic Republic of the)",
                "CF" => "Central African Republic",
                "CG" => "Congo",
                "CH" => "Switzerland",
                "CI" => "Cote D'ivoire",
                "CK" => "Cook Islands",
                "CL" => "Chile",
                "CM" => "Cameroon",
                "CN" => "China",
                "CO" => "Colombia",
                "CR" => "Costa Rica",
                "CU" => "Cuba",
                "CV" => "Cabo Verde",
                "CW" => "Curacao",
                "CY" => "Cyprus",
                "CZ" => "Czechia",
                "DE" => "Germany",
                "DJ" => "Djibouti",
                "DK" => "Denmark",
                "DM" => "Dominica",
                "DO" => "Dominican Republic",
                "DZ" => "Algeria",
                "EC" => "Ecuador",
                "EE" => "Estonia",
                "EG" => "Egypt",
                "ER" => "Eritrea",
                "ES" => "Spain",
                "ET" => "Ethiopia",
                "FI" => "Finland",
                "FJ" => "Fiji",
                "FK" => "Falkland Islands (Malvinas)",
                "FM" => "Micronesia (Federated States of)",
                "FO" => "Faroe Islands",
                "FR" => "France",
                "GA" => "Gabon",
                "GB" => "United Kingdom of Great Britain and Northern Ireland",
                "GD" => "Grenada",
                "GE" => "Georgia",
                "GF" => "French Guiana",
                "GG" => "Guernsey",
                "GH" => "Ghana",
                "GI" => "Gibraltar",
                "GL" => "Greenland",
                "GM" => "Gambia",
                "GN" => "Guinea",
                "GP" => "Guadeloupe",
                "GQ" => "Equatorial Guinea",
                "GR" => "Greece",
                "GS" => "South Georgia and The South Sandwich Islands",
                "GT" => "Guatemala",
                "GU" => "Guam",
                "GW" => "Guinea-Bissau",
                "GY" => "Guyana",
                "HK" => "Hong Kong",
                "HN" => "Honduras",
                "HR" => "Croatia",
                "HT" => "Haiti",
                "HU" => "Hungary",
                "ID" => "Indonesia",
                "IE" => "Ireland",
                "IL" => "Israel",
                "IM" => "Isle of Man",
                "IN" => "India",
                "IO" => "British Indian Ocean Territory",
                "IQ" => "Iraq",
                "IR" => "Iran (Islamic Republic of)",
                "IS" => "Iceland",
                "IT" => "Italy",
                "JE" => "Jersey",
                "JM" => "Jamaica",
                "JO" => "Jordan",
                "JP" => "Japan",
                "KE" => "Kenya",
                "KG" => "Kyrgyzstan",
                "KH" => "Cambodia",
                "KI" => "Kiribati",
                "KM" => "Comoros",
                "KN" => "Saint Kitts and Nevis",
                "KP" => "Korea (Democratic People's Republic of)",
                "KR" => "Korea (Republic of)",
                "KW" => "Kuwait",
                "KY" => "Cayman Islands",
                "KZ" => "Kazakhstan",
                "LA" => "Lao People's Democratic Republic",
                "LB" => "Lebanon",
                "LC" => "Saint Lucia",
                "LI" => "Liechtenstein",
                "LK" => "Sri Lanka",
                "LR" => "Liberia",
                "LS" => "Lesotho",
                "LT" => "Lithuania",
                "LU" => "Luxembourg",
                "LV" => "Latvia",
                "LY" => "Libya",
                "MA" => "Morocco",
                "MC" => "Monaco",
                "MD" => "Moldova (Republic of)",
                "ME" => "Montenegro",
                "MF" => "Saint Martin (French Part)",
                "MG" => "Madagascar",
                "MH" => "Marshall Islands",
                "MK" => "North Macedonia",
                "ML" => "Mali",
                "MM" => "Myanmar",
                "MN" => "Mongolia",
                "MO" => "Macao",
                "MP" => "Northern Mariana Islands",
                "MQ" => "Martinique",
                "MR" => "Mauritania",
                "MS" => "Montserrat",
                "MT" => "Malta",
                "MU" => "Mauritius",
                "MV" => "Maldives",
                "MW" => "Malawi",
                "MX" => "Mexico",
                "MY" => "Malaysia",
                "MZ" => "Mozambique",
                "NA" => "Namibia",
                "NC" => "New Caledonia",
                "NE" => "Niger",
                "NF" => "Norfolk Island",
                "NG" => "Nigeria",
                "NI" => "Nicaragua",
                "NL" => "Netherlands",
                "NO" => "Norway",
                "NP" => "Nepal",
                "NR" => "Nauru",
                "NU" => "Niue",
                "NZ" => "New Zealand",
                "OM" => "Oman",
                "PA" => "Panama",
                "PE" => "Peru",
                "PF" => "French Polynesia",
                "PG" => "Papua New Guinea",
                "PH" => "Philippines",
                "PK" => "Pakistan",
                "PL" => "Poland",
                "PM" => "Saint Pierre and Miquelon",
                "PR" => "Puerto Rico",
                "PS" => "Palestine, State of",
                "PT" => "Portugal",
                "PW" => "Palau",
                "PY" => "Paraguay",
                "QA" => "Qatar",
                "RE" => "Reunion",
                "RO" => "Romania",
                "RS" => "Serbia",
                "RU" => "Russian Federation",
                "RW" => "Rwanda",
                "SA" => "Saudi Arabia",
                "SB" => "Solomon Islands",
                "SC" => "Seychelles",
                "SD" => "Sudan",
                "SE" => "Sweden",
                "SG" => "Singapore",
                "SI" => "Slovenia",
                "SK" => "Slovakia",
                "SL" => "Sierra Leone",
                "SM" => "San Marino",
                "SN" => "Senegal",
                "SO" => "Somalia",
                "SR" => "Suriname",
                "SS" => "South Sudan",
                "ST" => "Sao Tome and Principe",
                "SV" => "El Salvador",
                "SX" => "Sint Maarten (Dutch Part)",
                "SY" => "Syrian Arab Republic",
                "SZ" => "Eswatini",
                "TC" => "Turks and Caicos Islands",
                "TD" => "Chad",
                "TG" => "Togo",
                "TH" => "Thailand",
                "TJ" => "Tajikistan",
                "TK" => "Tokelau",
                "TL" => "Timor-Leste",
                "TM" => "Turkmenistan",
                "TN" => "Tunisia",
                "TO" => "Tonga",
                "TR" => "Turkey",
                "TT" => "Trinidad and Tobago",
                "TV" => "Tuvalu",
                "TW" => "Taiwan (Province of China)",
                "TZ" => "Tanzania, United Republic of",
                "UA" => "Ukraine",
                "UG" => "Uganda",
                "UM" => "United States Minor Outlying Islands",
                "US" => "United States of America",
                "UY" => "Uruguay",
                "UZ" => "Uzbekistan",
                "VA" => "Holy See",
                "VC" => "Saint Vincent and The Grenadines",
                "VE" => "Venezuela (Bolivarian Republic of)",
                "VG" => "Virgin Islands (British)",
                "VI" => "Virgin Islands (U.S.)",
                "VN" => "Viet Nam",
                "VU" => "Vanuatu",
                "WF" => "Wallis and Futuna",
                "WS" => "Samoa",
                "YE" => "Yemen",
                "YT" => "Mayotte",
                "ZA" => "South Africa",
                "ZM" => "Zambia",
                "ZW" => "Zimbabwe",
            ])
            ->onlyOnForms();
    }
}